/*
 * API Pix
 * A API Pix padroniza serviços oferecidos pelo PSP recebedor no contexto do arranjo Pix, como criação de cobrança, verificação de Pix recebidos, devolução e conciliação. Os serviços expostos pelo PSP recebedor permitem ao usuário recebedor estabelecer integração de sua automação com os serviços Pix do PSP.  # Evolução da API Pix As seguintes mudanças são esperadas e consideradas retro-compatíveis (_backwards-compatibility_):  - Adição de novos recursos na API Pix. - Adição de novos parâmetros opcionais a cobranças. - Adição de novos campos em respostas da API Pix. - Alteração da ordem de campos. - Adição de novos elementos em enumerações  Mudanças compatíveis não geram nova versão da API Pix. Clientes devem estar preparados para lidar com essas mudanças sem quebrar.  Mudanças incompatíveis geram nova versão da API Pix.
 *
 * OpenAPI spec version: 2.1.0
 * Contact: suporte.ti@bcb.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ParametrosConsultaCob;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * CobsConsultadas
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-27T16:48:51.159Z[GMT]")
public class CobsConsultadas {
  @SerializedName("parametros")
  private ParametrosConsultaCob parametros = null;

  @SerializedName("cobs")
  private List<AllOfCobsConsultadasCobsItems> cobs = new ArrayList<AllOfCobsConsultadasCobsItems>();

  public CobsConsultadas parametros(ParametrosConsultaCob parametros) {
    this.parametros = parametros;
    return this;
  }

   /**
   * Get parametros
   * @return parametros
  **/
  @Schema(required = true, description = "")
  public ParametrosConsultaCob getParametros() {
    return parametros;
  }

  public void setParametros(ParametrosConsultaCob parametros) {
    this.parametros = parametros;
  }

  public CobsConsultadas cobs(List<AllOfCobsConsultadasCobsItems> cobs) {
    this.cobs = cobs;
    return this;
  }

  public CobsConsultadas addCobsItem(AllOfCobsConsultadasCobsItems cobsItem) {
    this.cobs.add(cobsItem);
    return this;
  }

   /**
   * Get cobs
   * @return cobs
  **/
  @Schema(required = true, description = "")
  public List<AllOfCobsConsultadasCobsItems> getCobs() {
    return cobs;
  }

  public void setCobs(List<AllOfCobsConsultadasCobsItems> cobs) {
    this.cobs = cobs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CobsConsultadas cobsConsultadas = (CobsConsultadas) o;
    return Objects.equals(this.parametros, cobsConsultadas.parametros) &&
        Objects.equals(this.cobs, cobsConsultadas.cobs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parametros, cobs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CobsConsultadas {\n");
    
    sb.append("    parametros: ").append(toIndentedString(parametros)).append("\n");
    sb.append("    cobs: ").append(toIndentedString(cobs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
