/*
 * API Pix
 * A API Pix padroniza serviços oferecidos pelo PSP recebedor no contexto do arranjo Pix, como criação de cobrança, verificação de Pix recebidos, devolução e conciliação. Os serviços expostos pelo PSP recebedor permitem ao usuário recebedor estabelecer integração de sua automação com os serviços Pix do PSP.  # Evolução da API Pix As seguintes mudanças são esperadas e consideradas retro-compatíveis (_backwards-compatibility_):  - Adição de novos recursos na API Pix. - Adição de novos parâmetros opcionais a cobranças. - Adição de novos campos em respostas da API Pix. - Alteração da ordem de campos. - Adição de novos elementos em enumerações  Mudanças compatíveis não geram nova versão da API Pix. Clientes devem estar preparados para lidar com essas mudanças sem quebrar.  Mudanças incompatíveis geram nova versão da API Pix.
 *
 * OpenAPI spec version: 2.1.0
 * Contact: suporte.ti@bcb.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DevolucaoHorario;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Devolucao
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-27T16:48:51.159Z[GMT]")
public class Devolucao {
  @SerializedName("id")
  private String id = null;

  @SerializedName("rtrId")
  private String rtrId = null;

  @SerializedName("valor")
  private String valor = null;

  @SerializedName("horario")
  private DevolucaoHorario horario = null;

  /**
   * Status da devolução.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    EM_PROCESSAMENTO("EM_PROCESSAMENTO"),
    DEVOLVIDO("DEVOLVIDO"),
    NAO_REALIZADO("NAO_REALIZADO");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("status")
  private StatusEnum status = null;

  public Devolucao id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Devolucao rtrId(String rtrId) {
    this.rtrId = rtrId;
    return this;
  }

   /**
   * ReturnIdentification que transita na PACS004.
   * @return rtrId
  **/
  @Schema(example = "D12345678202009091000abcde123456", required = true, description = "ReturnIdentification que transita na PACS004.")
  public String getRtrId() {
    return rtrId;
  }

  public void setRtrId(String rtrId) {
    this.rtrId = rtrId;
  }

  public Devolucao valor(String valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Valor a devolver.
   * @return valor
  **/
  @Schema(required = true, description = "Valor a devolver.")
  public String getValor() {
    return valor;
  }

  public void setValor(String valor) {
    this.valor = valor;
  }

  public Devolucao horario(DevolucaoHorario horario) {
    this.horario = horario;
    return this;
  }

   /**
   * Get horario
   * @return horario
  **/
  @Schema(required = true, description = "")
  public DevolucaoHorario getHorario() {
    return horario;
  }

  public void setHorario(DevolucaoHorario horario) {
    this.horario = horario;
  }

  public Devolucao status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status da devolução.
   * @return status
  **/
  @Schema(required = true, description = "Status da devolução.")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Devolucao devolucao = (Devolucao) o;
    return Objects.equals(this.id, devolucao.id) &&
        Objects.equals(this.rtrId, devolucao.rtrId) &&
        Objects.equals(this.valor, devolucao.valor) &&
        Objects.equals(this.horario, devolucao.horario) &&
        Objects.equals(this.status, devolucao.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rtrId, valor, horario, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Devolucao {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rtrId: ").append(toIndentedString(rtrId)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    horario: ").append(toIndentedString(horario)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
