/*
 * API Pix
 * A API Pix padroniza serviços oferecidos pelo PSP recebedor no contexto do arranjo Pix, como criação de cobrança, verificação de Pix recebidos, devolução e conciliação. Os serviços expostos pelo PSP recebedor permitem ao usuário recebedor estabelecer integração de sua automação com os serviços Pix do PSP.  # Evolução da API Pix As seguintes mudanças são esperadas e consideradas retro-compatíveis (_backwards-compatibility_):  - Adição de novos recursos na API Pix. - Adição de novos parâmetros opcionais a cobranças. - Adição de novos campos em respostas da API Pix. - Alteração da ordem de campos. - Adição de novos elementos em enumerações  Mudanças compatíveis não geram nova versão da API Pix. Clientes devem estar preparados para lidar com essas mudanças sem quebrar.  Mudanças incompatíveis geram nova versão da API Pix.
 *
 * OpenAPI spec version: 2.1.0
 * Contact: suporte.ti@bcb.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Paginacao
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-27T16:48:51.159Z[GMT]")
public class Paginacao {
  @SerializedName("paginaAtual")
  private Integer paginaAtual = null;

  @SerializedName("itensPorPagina")
  private Integer itensPorPagina = null;

  @SerializedName("quantidadeDePaginas")
  private Integer quantidadeDePaginas = null;

  @SerializedName("quantidadeTotalDeItens")
  private Integer quantidadeTotalDeItens = null;

  public Paginacao paginaAtual(Integer paginaAtual) {
    this.paginaAtual = paginaAtual;
    return this;
  }

   /**
   * Número da página recuperada.
   * minimum: 0
   * @return paginaAtual
  **/
  @Schema(required = true, description = "Número da página recuperada.")
  public Integer getPaginaAtual() {
    return paginaAtual;
  }

  public void setPaginaAtual(Integer paginaAtual) {
    this.paginaAtual = paginaAtual;
  }

  public Paginacao itensPorPagina(Integer itensPorPagina) {
    this.itensPorPagina = itensPorPagina;
    return this;
  }

   /**
   * Quantidade de registros retornado na página.
   * minimum: 1
   * @return itensPorPagina
  **/
  @Schema(required = true, description = "Quantidade de registros retornado na página.")
  public Integer getItensPorPagina() {
    return itensPorPagina;
  }

  public void setItensPorPagina(Integer itensPorPagina) {
    this.itensPorPagina = itensPorPagina;
  }

  public Paginacao quantidadeDePaginas(Integer quantidadeDePaginas) {
    this.quantidadeDePaginas = quantidadeDePaginas;
    return this;
  }

   /**
   * Quantidade de páginas disponíveis para consulta.
   * minimum: 1
   * @return quantidadeDePaginas
  **/
  @Schema(required = true, description = "Quantidade de páginas disponíveis para consulta.")
  public Integer getQuantidadeDePaginas() {
    return quantidadeDePaginas;
  }

  public void setQuantidadeDePaginas(Integer quantidadeDePaginas) {
    this.quantidadeDePaginas = quantidadeDePaginas;
  }

  public Paginacao quantidadeTotalDeItens(Integer quantidadeTotalDeItens) {
    this.quantidadeTotalDeItens = quantidadeTotalDeItens;
    return this;
  }

   /**
   * Quantidade total de itens disponíveis de acordo com os parâmetros informados.
   * minimum: 0
   * @return quantidadeTotalDeItens
  **/
  @Schema(required = true, description = "Quantidade total de itens disponíveis de acordo com os parâmetros informados.")
  public Integer getQuantidadeTotalDeItens() {
    return quantidadeTotalDeItens;
  }

  public void setQuantidadeTotalDeItens(Integer quantidadeTotalDeItens) {
    this.quantidadeTotalDeItens = quantidadeTotalDeItens;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Paginacao paginacao = (Paginacao) o;
    return Objects.equals(this.paginaAtual, paginacao.paginaAtual) &&
        Objects.equals(this.itensPorPagina, paginacao.itensPorPagina) &&
        Objects.equals(this.quantidadeDePaginas, paginacao.quantidadeDePaginas) &&
        Objects.equals(this.quantidadeTotalDeItens, paginacao.quantidadeTotalDeItens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paginaAtual, itensPorPagina, quantidadeDePaginas, quantidadeTotalDeItens);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Paginacao {\n");
    
    sb.append("    paginaAtual: ").append(toIndentedString(paginaAtual)).append("\n");
    sb.append("    itensPorPagina: ").append(toIndentedString(itensPorPagina)).append("\n");
    sb.append("    quantidadeDePaginas: ").append(toIndentedString(quantidadeDePaginas)).append("\n");
    sb.append("    quantidadeTotalDeItens: ").append(toIndentedString(quantidadeTotalDeItens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
