/*
 * API Pix
 * A API Pix padroniza serviços oferecidos pelo PSP recebedor no contexto do arranjo Pix, como criação de cobrança, verificação de Pix recebidos, devolução e conciliação. Os serviços expostos pelo PSP recebedor permitem ao usuário recebedor estabelecer integração de sua automação com os serviços Pix do PSP.  # Evolução da API Pix As seguintes mudanças são esperadas e consideradas retro-compatíveis (_backwards-compatibility_):  - Adição de novos recursos na API Pix. - Adição de novos parâmetros opcionais a cobranças. - Adição de novos campos em respostas da API Pix. - Alteração da ordem de campos. - Adição de novos elementos em enumerações  Mudanças compatíveis não geram nova versão da API Pix. Clientes devem estar preparados para lidar com essas mudanças sem quebrar.  Mudanças incompatíveis geram nova versão da API Pix.
 *
 * OpenAPI spec version: 2.1.0
 * Contact: suporte.ti@bcb.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ParametrosConsultaPix;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * PixConsultados
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-27T16:48:51.159Z[GMT]")
public class PixConsultados {
  @SerializedName("parametros")
  private ParametrosConsultaPix parametros = null;

  @SerializedName("pix")
  private List<AllOfPixConsultadosPixItems> pix = null;

  public PixConsultados parametros(ParametrosConsultaPix parametros) {
    this.parametros = parametros;
    return this;
  }

   /**
   * Get parametros
   * @return parametros
  **/
  @Schema(required = true, description = "")
  public ParametrosConsultaPix getParametros() {
    return parametros;
  }

  public void setParametros(ParametrosConsultaPix parametros) {
    this.parametros = parametros;
  }

  public PixConsultados pix(List<AllOfPixConsultadosPixItems> pix) {
    this.pix = pix;
    return this;
  }

  public PixConsultados addPixItem(AllOfPixConsultadosPixItems pixItem) {
    if (this.pix == null) {
      this.pix = new ArrayList<AllOfPixConsultadosPixItems>();
    }
    this.pix.add(pixItem);
    return this;
  }

   /**
   * Get pix
   * @return pix
  **/
  @Schema(description = "")
  public List<AllOfPixConsultadosPixItems> getPix() {
    return pix;
  }

  public void setPix(List<AllOfPixConsultadosPixItems> pix) {
    this.pix = pix;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PixConsultados pixConsultados = (PixConsultados) o;
    return Objects.equals(this.parametros, pixConsultados.parametros) &&
        Objects.equals(this.pix, pixConsultados.pix);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parametros, pix);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PixConsultados {\n");
    
    sb.append("    parametros: ").append(toIndentedString(parametros)).append("\n");
    sb.append("    pix: ").append(toIndentedString(pix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
