/*
 * API Pix
 * A API Pix padroniza serviços oferecidos pelo PSP recebedor no contexto do arranjo Pix, como criação de cobrança, verificação de Pix recebidos, devolução e conciliação. Os serviços expostos pelo PSP recebedor permitem ao usuário recebedor estabelecer integração de sua automação com os serviços Pix do PSP.  # Evolução da API Pix As seguintes mudanças são esperadas e consideradas retro-compatíveis (_backwards-compatibility_):  - Adição de novos recursos na API Pix. - Adição de novos parâmetros opcionais a cobranças. - Adição de novos campos em respostas da API Pix. - Alteração da ordem de campos. - Adição de novos elementos em enumerações  Mudanças compatíveis não geram nova versão da API Pix. Clientes devem estar preparados para lidar com essas mudanças sem quebrar.  Mudanças incompatíveis geram nova versão da API Pix.
 *
 * OpenAPI spec version: 2.1.0
 * Contact: suporte.ti@bcb.gov.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Webhook;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhookApi
 */
@Ignore
public class WebhookApiTest {

    private final WebhookApi api = new WebhookApi();

    /**
     * Cancelar o webhook Pix.
     *
     * Endpoint para cancelamento do webhook. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webhookDeleteTest() throws ApiException {
        api.webhookDelete();

        // TODO: test validations
    }
    /**
     * Exibir informações acerca do Webook Pix.
     *
     * Endpoint para recuperação de informações sobre o webhook pix. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webhookGetTest() throws ApiException {
        Webhook response = api.webhookGet();

        // TODO: test validations
    }
    /**
     * Configurar o Webhook Pix.
     *
     * Endpoint para configuração do serviço de notificações acerca de Pix recebidos. Somente Pix associados a um txid serão notificados. O Webhook é único por client ID. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void webhookPutTest() throws ApiException {
        Webhook body = null;
        api.webhookPut(body);

        // TODO: test validations
    }
}
